name: "Create Release"
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: npm install
        working-directory: ./plugin

      - name: Build
        run: npm run build
        working-directory: ./plugin

      - name: Release
        id: create_release
        name: "Create Release"
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: npm install
        working-directory: ./plugin

      - name: Build
        run: npm run build
        working-directory: ./plugin

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Obsidian x Todoist - v${{ github.ref }}
          draft: true
          files: |
            plugin/dist/main.js
            plugin/dist/manifest.json
            plugin/dist/styles.css

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Obsidian x Todoist - v${{ github.ref }}
          draft: true
          files: |
            plugin/dist/main.js
            plugin/dist/manifest.json
            plugin/dist/styles.css
